# Generated by Django 4.1 on 2024-12-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="password",
            field=models.CharField(
                default="12345", max_length=256, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
