# Generated by Django 4.1 on 2024-12-19 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_guest_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_items",
                        to="members.guest",
                        verbose_name="Guest",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_items",
                        to="members.item",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Item",
                "verbose_name_plural": "Guest Items",
            },
        ),
    ]
